version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #git-credential-helper: yes

phases:
  install:
    runtime-versions:
        php: 7.3
    commands:
    - echo checking PHP version.
    - php --version
      # - command
  pre_build:
    commands:
      - echo Entering nginxphp folder.
      - cd nginxphp
      
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nginxphp .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker tag nginxphp:latest 879888516627.dkr.ecr.us-east-1.amazonaws.com/nginx_php:latest
      - docker push 879888516627.dkr.ecr.us-east-1.amazonaws.com/nginx_php:latest

#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths