# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure_China_Internal'
    ScriptType: 'FilePath'
    ScriptPath: './AzureResourceManager/Deploy-AzTemplate.ps1'
    ScriptArguments: '-Location ''chinanorth2'' -ResourceGroupName ''armvscode'' -TemplateFile AzureResourceManager/azuredeploy.json'
    azurePowerShellVersion: 'LatestVersion'