apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # Update and install packages
    dpkg --configure -a
    apt-get update -y
    apt-get upgrade -y
    apt-get install -y singularity-container