apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-installer-config
  namespace: node-installer
data:
  install.sh: |
    #!/bin/bash

    # install dependencies
    apt-get install -y \
    build-essential \
    uuid-dev \
    libgpgme-dev \
    squashfs-tools \
    libseccomp-dev \
    wget \
    pkg-config \
    git \
    cryptsetup-bin

    # Download and install Golang
    export VERSION=1.18.2 OS=linux ARCH=amd64
    wget -t 0 -T 15 -c https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz
    sudo tar -C /usr/local -xzf go$VERSION.$OS-$ARCH.tar.gz

    export GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
    export GOROOT="/usr/local/go"
    export GOPATH="/home/go"
    export PATH=${PATH}:${GOROOT}/bin

    go version

    # Download Singularity
    export VERSION=3.9.9 && # adjust this to find the latest version
    mkdir -p $HOME/src/github.com/sylabs
    cd $HOME/src/github.com/sylabs
    wget -t 0 -T 15 -c https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-ce-${VERSION}.tar.gz
    tar -xzf singularity-ce-${VERSION}.tar.gz
    cd ./singularity-ce-${VERSION}

    export SINGULARITYPATH=/opt/singularity
    export PATH=${PATH}:${SINGULARITYPATH}/bin

    # Compile and install Singularity
    ./mconfig --prefix=$SINGULARITYPATH
    make -C ./builddir
    make -C ./builddir install