apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ['sh']
    args:
      - "-c"
      - |
        apt-get update -y
        apt-get upgrade -y
        apt-get install -y openssh-client
        /bin/sleep 3650d
    imagePullPolicy: IfNotPresent
  restartPolicy: Always